#!/bin/bash

VERSION_CODE=""
VERSION_TYPE=""
REGEX="^[0-9]+\.([0-9]+)\.[0-9]+$"
if [[ $CACHE_TAG =~ $REGEX ]]
then
	VERSION_CODE="$CACHE_TAG"
	RELEASE=${BASH_REMATCH[1]}
	if [ $((RELEASE%2)) -eq 0 ];
	then
		VERSION_TYPE="stable"
	else
		VERSION_TYPE="testing"
	fi
fi
docker build --build-arg VERSION_CODE=$VERSION_CODE \
	--build-arg VERSION_TYPE=$VERSION_TYPE -t $IMAGE_NAME .
