# A Docker BUILDER image with
# XTA (XA Transaction API) for Java language
# based on official OpenJDK image
FROM	lixa/xta-jdk AS builder
#
# Build without parameters to build latest
#	docker build -f Dockerfile-java-hello-mysql-postgresql -t lixa/xta-java-hello-mysql-postgresql .
#
# Inspect the image content with
#       docker run --rm -it lixa/xta-java-hello-mysql-postgresql bash
#
RUN	mkdir /myapp
COPY	HelloMysqlPostgresql.java /myapp
RUN	cd /myapp \
	&& javac -cp /opt/java/xta.jar:/opt/java/mariadb-java-client.jar:/opt/java/postgresql.jar HelloMysqlPostgresql.java

# Should use xta-jre, but at this time (2020-09-17) is support class versions
# up to 55.0, while xta-jdk produce class file version 58.0
# xta-jre is a derivative of openjdk:jre-slim
# xta-jdk is a derivative of openjdk:jdk-slim
#FROM	lixa/xta-jre
FROM	lixa/xta-jdk
COPY	--from=builder /myapp/*.class /myapp/
