CREATE USER IF NOT EXISTS 'lixa'@'%' IDENTIFIED BY 'passw0rd';
GRANT ALL ON lixa.* TO 'lixa'@'%';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS lixa;
CREATE TABLE IF NOT EXISTS lixa.authors (id INTEGER NOT NULL PRIMARY KEY, last_name TEXT, first_name TEXT) ENGINE=InnoDB;
