# A Dockerfile to build a sample program using
# XTA (XA Transaction API) for C language
FROM lixa/xta-c:latest
#
# Build without parameters to build latest
#	docker build -f Dockerfile-hello-postgresql -t lixa/xta-c-hello-postgresql .
#
# Inspect the image content with
#	docker run --rm -it lixa/xta-c-hello-postgresql bash
#
# Update Ubuntu Software repository
ARG 	DEBIAN_FRONTEND=noninteractive
# Copy source file to compile in /myapp
RUN	mkdir /myapp
COPY	hello-postgresql.c /myapp
# build sample program
RUN	BUILD_DEPS='gcc libxml2-dev libglib2.0-dev libpq-dev default-libmysqlclient-dev' \
	&& set -x \
	&& apt-get update && apt-get install -y --no-install-recommends \
		$BUILD_DEPS \
	&& cd /myapp \
	&& export PATH=$PATH:/opt/lixa/bin \
	&& gcc hello-postgresql.c $(lixa-config -x -c -f -l -d) -lpq -o hello-postgresql \
	&& apt-get purge -y --auto-remove $BUILD_DEPS \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/log/*
