# A Dockerfile to build a sample program using
# XTA (XA Transaction API) for C language
FROM lixa/xta-c:latest
#
# Build without parameters to build latest
#	docker build -f Dockerfile-hello-world -t lixa/xta-c-hello-world .
#
# Inspect the image content with
#	docker run --rm -it lixa/xta-c-hello-world bash
#
# Update Ubuntu Software repository
ARG 	DEBIAN_FRONTEND=noninteractive
# Copy source file to compile in /tmp
COPY	hello-world.c /tmp
# build sample program
RUN	BUILD_DEPS='make gcc libxml2-dev libglib2.0-dev libpq-dev' \
	&& set -x \
	&& apt-get update && apt-get install -y --no-install-recommends \
		libpq5 default-libmysqlclient-dev $BUILD_DEPS \
	&& cd /tmp \
	&& export PATH=$PATH:/opt/lixa/bin \
	&& gcc hello-world.c $(lixa-config -x -c -f -l -d) -lpq $(mysql_config --libs_r) -o hello-world \
	&& apt-get purge -y --auto-remove $BUILD_DEPS \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/log/*
